site_name: OpenBaton Documentation
pages:
- ['index.md', 'Get Started', 'Get Started']
- ['nfvo-installation.md', 'Installation', 'Install Open Baton']
- ['use.md', 'Use it', 'Introduction']
- ['vim-instance.md', 'Use it', 'Register a PoP']
- ['vnfm-generic.md', 'Use it', 'Generic VNFM']
- ['vnfm-how-to-write.md', 'Use it', 'Write your own VNFM']
- ['vnfm-vendor-specific.md', 'Use it', 'Integrate your own VNFM']
- ['vnfpackage.md', 'Use it', 'Create your own VNF Package']
- ['ns-descriptor.md', 'Use it', 'Create the NSD']
- ['nfvo-how-to-use-gui.md', 'Use it', 'Use via the Dashboard']
- ['nfvo-sdk.md', 'Use it', 'Use via the SDK']
- ['zabbix-plugin.md', 'Use it', 'Use Zabbix plugin']
- ['integration-test-use.md', 'Use it', 'Integration Tests']
- ['tosca-iperf-scenario.md', 'Use it', 'TOSCA iperf scenario']
- ['tosca-CSAR-onboarding.md', 'Use it', 'TOSCA CSAR on-boarding']
- ['dummy-NSR.md', 'Tutorials', 'Dummy NSR']
- ['iperf-NSR.md', 'Tutorials', 'Iperf Scenario']
- ['ims-NSR.md', 'Tutorials', 'OpenIMSCore example']
- ['extend.md', 'Extend it', 'Extend it']
- ['nfvo-architecture.md', 'Extend it', 'NFVO Architecture']
- ['vim-plugin.md', 'Extend it', 'Write your own Plugin']
- ['FAQ.md', 'FAQ', 'FAQ']
- ['**HIDDEN**': 'vnf-descriptor.md']
- ['**HIDDEN**': 'zabbix-server-configuration.md']
- ['**HIDDEN**': 'vnfr-states.md']
- ['**HIDDEN**': 'vnf-parameters.md']
- ['**HIDDEN**': 'nsd-json-example.md']
- ['**HIDDEN**': 'integration-test-write.md']
google_analytics: ['UA-68429895-1', 'openbaton.github.io']
theme: readthedocs
theme_dir: 'custom_theme'

