site_name: OpenBaton Documentation
pages:
- ['index.md', 'Get Started', 'Get Started']
- ['nfvo-installation.md', 'Installation', 'Overview']
- ['nfvo-installation-deb.md', 'Installation', 'Install on Linux']
- ['nfvo-installation-mac.md', 'Installation', 'Install on MacOS']
- ['nfvo-installation-docker.md', 'Installation', 'Install with Docker']
- ['nfvo-installation-vagrant.md', 'Installation', 'Install with Vagrant']
- ['nfvo-configuration.md', 'Installation', 'Configure it']
- ['use.md', 'NFV Orchestrator', 'NFVO intro']
- ['security.md', 'NFV Orchestrator', 'Identity management']
- ['nfvo-how-to-use-gui.md', 'NFV Orchestrator', 'Use via the Dashboard']
- ['nfvo-how-to-use-cli.md', 'NFV Orchestrator', 'Use via the CLI']
- ['vim-instance.md', 'NFV Orchestrator', 'Register a PoP']
- ['vnf-package.md', 'NFV Orchestrator', 'VNF Packages']
- ['ns-descriptor.md', 'NFV Orchestrator', 'Network Service Descriptor']
- ['vnfm-intro.md', 'VNF Managers', 'VNFM intro']
- ['vnfm-generic.md', 'VNF Managers', 'Generic VNFM']
- ['vnfm-juju.md', 'VNF Managers', 'Juju VNFM']
- ['vim-driver.md', 'VIM Driver', 'VIM Driver Overview']
- ['vnfm-how-to-write.md', 'VNF Managers', 'Develop a VNFM']
- ['vnfm-vendor-specific.md', 'VNF Managers', 'Integrate your own VNFM']
- ['monitoring.md', 'Monitoring', 'Monitoring overview']
- ['zabbix-plugin.md', 'Monitoring', 'Zabbix plugin']
- ['autoscaling.md', 'Autoscaling', 'Autoscaling overview']
- ['fault-management.md', 'Fault Management', 'FM overview']
- ['network-slicing.md', 'Network Slicing', 'NS overview']
- ['marketplace.md', 'Marketplace', 'Marketplace overview']
- ['tutorial.md', 'Tutorials', 'Tutorials overview']
- ['dummy-NSR.md', 'Tutorials', 'Dummy NSR']
- ['iperf-NSR.md', 'Tutorials', 'Iperf Scenario']
- ['ims-NSR.md', 'Tutorials', 'OpenIMSCore example']
- ['tutorial-sipp.md', 'Tutorials', 'SIPp example']
- ['fms-sipp-tutorial.md', 'Tutorials', 'Fault Management System']
- ['integration-test-use.md', 'Tutorials', 'Integration Tests']
- ['nfvo-architecture.md', 'Learn more', 'NFVO Architecture']
- ['vim-driver-create.md', 'Learn more', 'Create a VIM Driver']
- ['nfvo-sdk.md', 'Learn more', 'Open Baton SDKs']
- ['how-to-register-event.md', 'Learn more','The Event Mechanism tutorial']
- ['FAQ.md', 'FAQ', 'FAQ']
- ['**HIDDEN**': 'vnf-descriptor.md']
- ['**HIDDEN**': 'nfvo-installation-src.md']
- ['**HIDDEN**': 'zabbix-server-configuration.md']
- ['**HIDDEN**': 'tosca-iperf-scenario.md']
- ['**HIDDEN**': 'tosca-dummy-nsr.md']
- ['**HIDDEN**': 'tosca-ims.md']
- ['**HIDDEN**': 'tosca-vnfd.md']
- ['**HIDDEN**': 'tosca-nsd.md']
- ['**HIDDEN**': 'tosca-CSAR-onboarding.md']
- ['**HIDDEN**': 'vnfr-states.md']
- ['**HIDDEN**': 'vnf-parameters.md']
- ['**HIDDEN**': 'nsd-json-example.md']
- ['**HIDDEN**': 'integration-test-write.md']
google_analytics: ['UA-68429895-1', 'openbaton.github.io']
theme: readthedocs
theme_dir: 'custom_theme'
repo_url: https://github.com/openbaton
repo_name: OpenBaton GitHub
site_favicon: favicon.ico
copyright: Copyright (c) 2016 Open Baton (http://www.openbaton.org)
