site_name: OpenBaton Documentation
pages:
- ['index.md', 'Overview', 'Overview']
- ['nfvo-installation.md', 'Installation', 'Overview']
- ['nfvo-installation-deb.md', 'Installation', 'Install on Linux']
- ['nfvo-installation-mac.md', 'Installation', 'Install on MacOS']
- ['nfvo-installation-docker.md', 'Installation', 'Install with Docker']
- ['nfvo-installation-vagrant.md', 'Installation', 'Install with Vagrant']
- ['nfvo-configuration.md', 'Installation', 'Configure it']
- ['use.md', 'Get Started', 'Get Started']
- ['pop-registration.md', 'Get Started', 'Register a PoP']
- ['vnf-package.md', 'Get Started', 'Build your VNF Package']
- ['vnf-package-onboard.md', 'Get Started', 'On board your VNF Package']
- ['ns-descriptor.md', 'Get Started', 'Build your Network Service Descriptor']
- ['ns-descriptor-onboard.md', 'Get Started', 'On board your Network Service Descriptor']
- ['launch-nsd.md', 'Get Started', 'Launch your Network Service']
- ['tutorial.md', 'Tutorials', 'Tutorials overview']
- ['dummy-NSR.md', 'Tutorials', 'Dummy NS']
- ['iperf-NSR.md', 'Tutorials', 'Iperf NS']
- ['tutorial-sipp.md', 'Tutorials', 'SIPp NS']
- ['ims-NSR.md', 'Tutorials', 'OpenIMSCore NS']
- ['tutorial-juju.md', 'Tutorials', 'OpenIMSCore NS with Juju VNFM']
- ['fms-sipp-tutorial.md', 'Tutorials', 'Fault Management System']
- ['nfvo-how-to-use-gui.md', 'User Tools', 'Dashboard']
- ['nfvo-how-to-use-cli.md', 'User Tools', 'CLI']
- ['nfvo-sdk.md', 'User Tools', 'Open Baton SDKs']
- ['api.md', 'User Tools', 'NFVO REST APIs']
- ['vim-driver.md', 'VIM Drivers', 'VIM drivers overview']
- ['openstack-driver.md', 'VIM Drivers', 'OpenStack VIM Driver']
- ['test-driver.md', 'VIM Drivers', 'Test VIM Driver']
- ['vim-driver-create.md', 'VIM Drivers', 'Build your own VIM Driver']
- ['vnfm-intro.md', 'VNF Managers', 'VNFM overview']
- ['vnfm-generic.md', 'VNF Managers', 'Generic VNFM']
- ['vnfm-juju.md', 'VNF Managers', 'Juju VNFM']
- ['vnfm-how-to-write.md', 'VNF Managers', 'Develop a VNFM']
- ['vnfm-vendor-specific.md', 'VNF Managers', 'Integrate your own VNFM']
- ['monitoring.md', 'Monitoring', 'Monitoring overview']
- ['zabbix-plugin.md', 'Monitoring', 'Zabbix plugin']
- ['services.md', 'Services', 'Services overview']
- ['autoscaling.md', 'Services', 'Autoscaling overview']
- ['fault-management.md', 'Services', 'FM overview']
- ['network-slicing.md', 'Services', 'NS overview']
- ['marketplace.md', 'Marketplace', 'Marketplace overview']
- ['nfvo-architecture.md', 'Learn More', 'NFVO Architecture']
- ['how-to-register-event.md', 'Learn More','The Event Engine']
- ['security.md', 'Learn More', 'Identity management']
- ['integration-test-use.md', 'Learn More', 'Continuous Integration']

- ['FAQ.md', 'FAQ', 'FAQ']
- ['**HIDDEN**': 'amazon-driver.md']
- ['**HIDDEN**': 'docker-driver.md']
- ['**HIDDEN**': 'how-to-ec2-cli.md']
- ['**HIDDEN**': 'how-to-ec2-dashboard.md']
- ['**HIDDEN**': 'integration-test-write.md']
- ['**HIDDEN**': 'nfvo-installation-src.md']
- ['**HIDDEN**': 'nsd-json-example.md']
- ['**HIDDEN**': 'pop-amazon.md']
- ['**HIDDEN**': 'pop-docker.md']
- ['**HIDDEN**': 'pop-openstack.md']
- ['**HIDDEN**': 'pop-test.md']
- ['**HIDDEN**': 'tosca-iperf-scenario.md']
- ['**HIDDEN**': 'tosca-dummy-nsr.md']
- ['**HIDDEN**': 'tosca-ims.md']
- ['**HIDDEN**': 'tosca-vnfd.md']
- ['**HIDDEN**': 'tosca-nsd.md']
- ['**HIDDEN**': 'tosca-CSAR-onboarding.md']
- ['**HIDDEN**': 'tosca-fm.md']
- ['**HIDDEN**': 'tosca-asp.md']
- ['**HIDDEN**': 'tosca-iperf-scenario.md']
- ['**HIDDEN**': 'tosca-CSAR-onboarding.md']
- ['**HIDDEN**': 'vnfr-states.md']
- ['**HIDDEN**': 'vnf-dependencies.md']
- ['**HIDDEN**': 'vnf-dependencies-generic.md']
- ['**HIDDEN**': 'vnf-parameters.md']
- ['**HIDDEN**': 'vnf-descriptor.md']
- ['**HIDDEN**': 'vnfm-generic-configuration.md']
- ['**HIDDEN**': 'zabbix-server-configuration-3.0.md']
- ['**HIDDEN**': 'zabbix-server-configuration-2.2.md']

google_analytics: ['UA-68429895-1', 'openbaton.github.io']
theme: readthedocs
theme_dir: 'custom_theme'
repo_url: https://github.com/openbaton
repo_name: OpenBaton GitHub
site_favicon: favicon.ico

